### ISSUE TITLE
data branch

### ISSUE THREAD

**Issue by kebeleicsaba** [Uni-Sopron/dtr-o21-beadando-kebelei-forma1#1]
@hegyhati Létrehoztam egy data branch-et, de asszem felülírta a maint-t. A terv az volt, hogy majd egy pull request-en keresztül kérek véleményt a data fájlról.

**Comment by hegyhati** [comment]
Hat annyit latok, hogy most csak egy data branch van, azon 4 commit, es semmi mas :-D Hogy ezt hogy csinaltad, azt nem tudom :-D (marmint azt tudom, hogy lehet ilyet csinalni, de hogy Neked hogy sikerult, azt nem :-D)

A `lap_options`-t en nem tennem ki setbe, ez a modell magva, nem fogod ezt masik feladatnal boviteni, vagy csokkenteni, meg fugg a logika attol, melyiket valasztod, stb.

Adj a dolgoknak mertekegysegeket.

tyre compoundsra van minimalis szam, vagy a cserekre? nem ismerem a szabalyokat, de nekem utobbi remlik.

**Comment by kebeleicsaba** [comment]
Pedig a gépemnél a git log az a következő:
```bash
commit d431d66a2cdea8c13578716eae32e24a755499f1 (HEAD -> data, origin/data)
Author: Kebelei Csaba <71121076+kebeleicsaba@users.noreply.github.com>     
Date:   Fri Dec 31 20:59:20 2021 +0100

    Fixed number_of_laps

commit 6b5a1d27096485966a7c85304547943e5bb184af
Author: Kebelei Csaba <71121076+kebeleicsaba@users.noreply.github.com>     
Date:   Fri Dec 31 15:50:42 2021 +0100

    Update data

commit b5f96ec635c87ad1e66f992a77e3449ebffa28b1
Author: Kebelei Csaba <71121076+kebeleicsaba@users.noreply.github.com>     
Date:   Fri Dec 31 14:38:45 2021 +0100

    Add data

commit 6c6e1f9f9c1e42a2cfb36b26efb6948054a548a6 (main)
Author: Kebelei Csaba <71121076+kebeleicsaba@users.noreply.github.com>     
Date:   Fri Dec 31 13:54:36 2021 +0100

    Init files
```

És akkor a döntésem az lehetne egyszerűen, hogy `var strategy{race_length, tyre_compounds} binary;`? 

Megnéztem a szabályt, miszerint: 
Cars must race on any 2 dry compounds during a race unless intermediate or wet tyres have been used by that car in that race.
A modellbe csak a száraz gumikkal foglalkoznék. 😁

**Comment by kebeleicsaba** [comment]
Közben rájöttem, hogy hiányzik az, hogy minnél keményebb tyre compound, annál lassabak vagyunk. Ötleteltem még a változókon és elég fejvakarós lett a dolog. Az értelmes lenne, ha lenne egy döntés, hogy melyik körön melyik tyre compound-ot használjuk és mellete redundáns változóként, hogy melyik körben megyünk kereket cserélni, illetve egy változó lehetne, hogy melyik körben mennyi a köridő. 😅

**Comment by hegyhati** [comment]
A `git log`-os megjegyzesedet nem ertem. Pontosan ezt latom itt is, szoval mire akartal ebbol celozni?

A dontesi valtozot tobbfelekeppen felveheted. Kerdes, hogy mi a logikusabb, de ezt akkor lehet latni, ha fix az, hogy mit akarsz csinalni. Mindenesetre mondjuk 4 fele gumitipus es egy 60 koros verseny esetben 240 valtozot letrehozni azert, hogy meglegyen az a 3 informacio, hogy mi az aleos gumi, mi a masodik, es mikor csereled le.... hat kicsit overkill. 

De, fel lehet irni igy is a modellt.
